name: Chart Dev CI

on: [pull_request]

jobs:
  lint_test_package_development:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Helm 3
      uses: Azure/setup-helm@v1
      with:
        version: 'v3.1.0'

    - name: Lint charts
      run: ls -d charts/* | xargs helm lint

    - name: Create kind cluster
      uses: helm/kind-action@v1.0.0-alpha.3
      with:
        install_local_path_provisioner: true

    - name: Install charts
      run: ls -d charts/* | xargs helm install -g

    - name: Save charts locally and push to remote registry
      run: |
        export HELM_EXPERIMENTAL_OCI=1
        helm version
        az acr login --name nhsuk

        # test pushing specific chart
        helm chart save ./charts/tester/ nhsuk.azurecr.io/helm/tester-direct:latest
        helm chart push nhsuk.azurecr.io/helm/tester-direct:latest

        az account show
        ls -d charts/* | xargs -I {} -- sh -c 'helm chart save ./{} nhsuk.azurecr.io/helm/$(basename {}):$(helm show chart {} | grep version | cut -d " " -f 2)-$(git rev-parse --short HEAD:./{})'
        helm chart list
        ls -d charts/* | xargs -I {} -- sh -c 'helm chart push nhsuk.azurecr.io/helm/$(basename {}):$(helm show chart {} | grep version | cut -d " " -f 2)-$(git rev-parse --short HEAD:./{})'
