name: CI

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Helm 3
      uses: Azure/setup-helm@v1
      with:
        version: 'v3.1.0'

    - name: Lint charts
      run: ls -d charts/* | xargs helm lint

    - name: Create kind cluster
      uses: helm/kind-action@v1.0.0-alpha.3
      with:
        install_local_path_provisioner: true
      # Only build a kind cluster if there are chart changes to test.
      if: steps.lint.outputs.changed == 'true'

    - name: Install charts
      run: ls -d charts/* | xargs helm install -g
      if: steps.lint.outputs.changed == 'true'
