name: Merge to master CI

on:
  push:
    # TODO: Uncomment after testing
    # branches:
    #   - master

jobs:
  lint_test_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Helm 3
      uses: Azure/setup-helm@v1
      with:
        version: 'v3.1.0'

    - name: Lint charts
      run: ls -d charts/* | xargs helm lint

    - name: Create kind cluster
      uses: helm/kind-action@v1.0.0-alpha.3
      with:
        install_local_path_provisioner: true

    - name: Install charts
      run: ls -d charts/* | xargs helm install -g

    - name: Save charts locally and push to remote registry
      run: |
        az acr login --name nhsuk
        export HELM_EXPERIMENTAL_OCI=1
        ls -d charts/* | xargs -I {} -- sh -c 'helm chart save ./{} nhsuk.azurecr.io/helm/$(basename {}):$(helm show chart {} | grep version | cut -d " " -f 2)'
        ls -d charts/* | xargs -I {} -- sh -c 'helm chart push nhsuk.azurecr.io/helm/$(basename {}):$(helm show chart {} | grep version | cut -d " " -f 2)'
